"""Guion completo de LA GUERRA FRÍA — la historia entera, contada en detalle.

Mismas reglas fijas del proyecto (estilo definitivo del alunizaje):
  * Narrador único: Dark.
  * Los nombres en inglés/ruso se escriben como suenan (Truman -> Trúman).
  * Las fechas y los años van SIEMPRE en cifras.
  * Letra estática mientras se escribe, mano opción 2, sin música, sin pie.
  * Un dibujo propio por escena: nunca se repite.

Cada entrada: S(texto, pausa, imagen, titulo, subtitulo)
"""


def S(texto, pausa=0.35, img=None, t1=None, t2=None):
    return dict(txt=texto, gap=pausa, img=img,
                t1=t1.split('|') if t1 else None,
                t2=t2.split('|') if t2 else None)


GUION = [
    # ------------------------------------------------------------- 1. APERTURA
    S("Imaginate una guerra donde los dos ejércitos más grandes de la historia nunca se dispararon un solo tiro.", 0.5,
      None, "LA GUERRA FRÍA", "LA HISTORIA COMPLETA"),
    S("Duró cuarenta y cinco años. Partió el mundo en dos mitades. Y estuvo tres veces a punto de terminar con todo.", 0.55,
      None, "45 AÑOS", "EL MUNDO PARTIDO|EN DOS MITADES"),
    S("No hubo trincheras. Hubo espías, muros, cohetes, radios, películas, mentiras y silencio.", 0.5,
      None, "NI UNA TRINCHERA", "ESPÍAS, MUROS,|COHETES Y MENTIRAS"),
    S("Y todo empezó, como suelen empezar estas cosas, el día que terminó otra guerra mucho peor.", 0.55,
      None, "TODO EMPIEZA", "CUANDO TERMINA|OTRA GUERRA"),
    S("Esta es la historia completa. Con los nombres, las fechas, los errores... y las veces que casi nos matamos a todos.", 0.6,
      None, "LA HISTORIA|COMPLETA", "NOMBRES. FECHAS.|ERRORES."),

    # ------------------------------------------------- 2. 1945: EL MUNDO ROTO
    S("Mayo de 1945. Europa es un tendal de escombros. Ciudades enteras sin techo, sin agua, sin nombre.", 0.45,
      None, "MAYO DE 1945", "EUROPA ES UN|TENDAL DE ESCOMBROS"),
    S("Murieron entre sesenta y setenta millones de personas. Es como si desapareciera hoy toda Italia. Entera.", 0.55,
      None, "70 MILLONES|DE MUERTOS", "COMO SI DESAPARECIERA|ITALIA ENTERA"),
    S("Los viejos dueños del mundo quedaron de rodillas. Inglaterra, arruinada. Francia, humillada. Alemania, borrada del mapa.", 0.5,
      None, "LOS VIEJOS DUEÑOS", "INGLATERRA, FRANCIA,|ALEMANIA: DE RODILLAS"),
    S("Y en ese hueco quedaron parados dos países que apenas veinte años antes nadie tomaba muy en serio.", 0.5,
      None, "QUEDA UN HUECO", "Y DOS PAÍSES|LO OCUPAN"),
    S("Estados Unidos, que salió de la guerra más rico que cuando entró, con la mitad de la producción del planeta.", 0.5,
      None, "ESTADOS UNIDOS", "SALE MÁS RICO|QUE COMO ENTRÓ"),
    S("Y la Unión Soviética, que salió destruida, con veintisiete millones de muertos, pero con el ejército más grande del mundo parado en el centro de Europa.", 0.6,
      None, "UNIÓN SOVIÉTICA", "27 MILLONES DE MUERTOS|Y EL MAYOR EJÉRCITO"),
    S("Fueron aliados durante cuatro años. Se necesitaron. Se mandaron camiones, aviones, comida y abrazos por radio.", 0.45,
      None, "FUERON ALIADOS", "CUATRO AÑOS|SE NECESITARON"),
    S("Pero era una amistad de circunstancia. Como esos dos que se juntan solo porque tienen el mismo enemigo.", 0.5,
      None, "AMISTAD DE|CIRCUNSTANCIA", "EL MISMO ENEMIGO|Y NADA MÁS"),
    S("Muerto el enemigo, se miraron a la cara. Y no les gustó nada lo que vieron.", 0.6,
      None, "MUERTO EL ENEMIGO", "SE MIRARON|A LA CARA"),

    # ---------------------------------------------------- 3. YALTA Y POTSDAM
    S("Febrero de 1945. Todavía faltaban tres meses para el final, y ya se estaban repartiendo la torta.", 0.45,
      None, "FEBRERO DE 1945", "SE REPARTEN|LA TORTA"),
    S("Yalta, en Crimea, un balneario del Mar Negro. Tres hombres sentados en unos sillones deciden el destino de mil millones de personas.", 0.5,
      None, "YALTA, CRIMEA", "TRES HOMBRES|EN TRES SILLONES"),
    S("Rúsvelt, el americano, enfermo y cansado: le quedaban dos meses de vida y él ya lo sabía.", 0.45,
      None, "ROOSEVELT", "ENFERMO.|LE QUEDAN 2 MESES"),
    S("Chérchil, el inglés, con su puro, hablando fuerte para tapar que ya no mandaba casi nada.", 0.45,
      None, "CHURCHILL", "HABLA FUERTE|PARA TAPAR ALGO"),
    S("Y Stálin, el georgiano, callado, tomando notas, con seis millones de soldados ya adentro de Europa del Este.", 0.55,
      None, "STALIN", "CALLADO, CON|6 MILLONES DE SOLDADOS"),
    S("Stálin no necesitaba negociar. Él ya tenía puesto lo que los otros dos le estaban por conceder en un papel.", 0.5,
      None, "NO NECESITABA|NEGOCIAR", "YA TENÍA PUESTO|LO QUE PEDÍA"),
    S("Se acordó dividir Alemania en cuatro zonas. Y prometer elecciones libres en Polonia. Esa promesa duró exactamente lo que tardó el avión en despegar.", 0.55,
      None, "ELECCIONES LIBRES|EN POLONIA", "LA PROMESA DURÓ|LO QUE EL DESPEGUE"),
    S("Julio de 1945. Segunda reunión, en Potsdam, a las afueras de Berlín, entre ruinas todavía humeantes.", 0.45,
      None, "JULIO DE 1945", "POTSDAM, ENTRE|RUINAS HUMEANTES"),
    S("Pero cambiaron los actores. Rúsvelt había muerto. Ahora estaba Jarri Trúman, un ex vendedor de camisas de Misuri.", 0.5,
      None, "HARRY TRUMAN", "UN EX VENDEDOR|DE CAMISAS"),
    S("Y Trúman llegó con un secreto en el bolsillo que le cambiaba la voz cuando hablaba.", 0.5,
      None, "LLEGÓ CON|UN SECRETO", "EN EL BOLSILLO"),
    S("El 16 de julio, en el desierto de Nuevo México, los Estados Unidos habían hecho explotar la primera bomba atómica de la historia.", 0.55,
      None, "16 DE JULIO", "LA PRIMERA BOMBA|ATÓMICA DE LA HISTORIA"),
    S("Trúman se lo comentó a Stálin como al pasar: tenemos un arma nueva, de una fuerza inusual.", 0.45,
      None, "«UN ARMA NUEVA»", "«DE UNA FUERZA|INUSUAL»"),
    S("Stálin apenas asintió. Qué bueno, dijo. Úsenla contra Japón. Y siguió comiendo, como si nada.", 0.5,
      None, "«QUÉ BUENO.|ÚSENLA»", "Y SIGUIÓ COMIENDO"),
    S("Lo que Trúman no sabía es que Stálin estaba mucho mejor informado que él. Sus espías le habían contado todo hacía meses.", 0.6,
      None, "STALIN YA SABÍA", "SUS ESPÍAS SE LO|CONTARON HACE MESES"),
    S("Esa noche, Stálin llamó a Moscú y dio una sola orden: aceleren nuestro proyecto. Todo lo que haga falta.", 0.6,
      None, "ESA NOCHE|LLAMA A MOSCÚ", "«ACELEREN NUESTRO|PROYECTO»"),

    # --------------------------------------- 4. HIROSHIMA Y EL NUEVO MIEDO
    S("6 de agosto de 1945. Jiroshima. Ochenta mil personas mueren en un segundo. Una sola bomba, un solo avión.", 0.55,
      None, "6 DE AGOSTO|DE 1945", "HIROSHIMA:|80.000 EN UN SEGUNDO"),
    S("Tres días después, Nagasaki. Japón se rinde. Termina la Segunda Guerra Mundial. Y empieza otra cosa.", 0.55,
      None, "NAGASAKI", "TERMINA UNA GUERRA|Y EMPIEZA OTRA"),
    S("Porque desde ese día la humanidad tiene un botón que puede apagarse a sí misma. Y hay que decidir quién lo toca.", 0.6,
      None, "APARECE EL BOTÓN", "AHORA HAY QUE|DECIDIR QUIÉN LO TOCA"),
    S("Óppenjaimer, el físico que dirigió el proyecto, dijo aquella frase: ahora me he convertido en la muerte, destructor de mundos.", 0.6,
      None, "OPPENHEIMER", "«ME CONVERTÍ|EN LA MUERTE»"),
    S("Durante cuatro años, Estados Unidos fue el único país del planeta con la bomba. Cuatro años de ventaja absoluta.", 0.5,
      None, "CUATRO AÑOS", "EL ÚNICO PAÍS|CON LA BOMBA"),
    S("Y esos cuatro años definieron todo lo que viene ahora.", 0.6,
      None, "ESOS 4 AÑOS", "DEFINEN TODO|LO QUE SIGUE"),

    # ---------------------------------------------------- 5. EL TELÓN DE ACERO
    S("Mientras tanto, en Europa del Este pasaba algo raro. Los soviéticos habían liberado ocho países de los nazis. Y no se iban.", 0.5,
      None, "LIBERARON|OCHO PAÍSES", "Y NO SE IBAN"),
    S("Polonia, Hungría, Rumania, Bulgaria, Checoslovaquia, Alemania del Este. Uno por uno, gobiernos comunistas.", 0.5,
      None, "UNO POR UNO", "GOBIERNOS|COMUNISTAS"),
    S("El método siempre era el mismo, y tenía nombre: la táctica del salame. Se corta finito, de a una rodaja.", 0.5,
      None, "LA TÁCTICA|DEL SALAME", "SE CORTA FINITO,|DE A UNA RODAJA"),
    S("Primero un gobierno de coalición. Después los comunistas se quedan con el Ministerio del Interior, o sea, con la policía.", 0.5,
      None, "PRIMERO:|COALICIÓN", "DESPUÉS: LA POLICÍA"),
    S("Con la policía en la mano, los otros partidos empiezan a tener accidentes. Elecciones raras. Y un día quedó uno solo.", 0.55,
      None, "LOS OTROS TIENEN|«ACCIDENTES»", "Y UN DÍA|QUEDA UNO SOLO"),
    S("Marzo de 1946. Chérchil viaja a un pueblito de Misuri y da un discurso que le pone nombre a la época.", 0.45,
      None, "MARZO DE 1946", "UN DISCURSO EN|UN PUEBLITO"),
    S("Desde Stettin, en el Báltico, hasta Trieste, en el Adriático, un telón de acero ha caído sobre el continente.", 0.6,
      None, "«UN TELÓN|DE ACERO»", "«HA CAÍDO SOBRE|EL CONTINENTE»"),
    S("Esa frase, telón de acero, dio la vuelta al mundo en un día. Porque describía algo que todos veían y nadie se animaba a nombrar.", 0.55,
      None, "TELÓN DE ACERO", "TODOS LO VEÍAN.|NADIE LO NOMBRABA."),
    S("Stálin respondió furioso: llamó a Chérchil incendiario de guerra. Pero no negó ni una sola palabra.", 0.6,
      None, "STALIN RESPONDE", "PERO NO NIEGA|NI UNA PALABRA"),

    # ------------------------------------------- 6. TRUMAN Y EL PLAN MARSHALL
    S("Febrero de 1947. Inglaterra manda un mensaje que suena a rendición: no podemos seguir sosteniendo a Grecia y Turquía.", 0.5,
      None, "FEBRERO DE 1947", "«NO PODEMOS|SOSTENERLAS MÁS»"),
    S("Traducción: si ustedes no entran, esos dos países se caen del lado soviético en seis meses.", 0.5,
      None, "TRADUCCIÓN:", "«SI NO ENTRAN,|SE CAEN»"),
    S("Trúman va al Congreso y dice la frase que va a gobernar los siguientes cuarenta años de política mundial.", 0.5,
      None, "TRUMAN VA|AL CONGRESO", "Y DICE LA FRASE|DE LA ÉPOCA"),
    S("Estados Unidos apoyará a los pueblos libres que resistan ser sometidos. En cualquier lugar del mundo.", 0.55,
      None, "DOCTRINA TRUMAN", "«EN CUALQUIER LUGAR|DEL MUNDO»"),
    S("En cualquier lugar del mundo. Eso es una promesa enorme. Y también un cheque en blanco.", 0.55,
      None, "UNA PROMESA|ENORME", "Y UN CHEQUE|EN BLANCO"),
    S("La estrategia tenía nombre técnico: contención. No atacar a la Unión Soviética, pero no dejarla crecer ni un centímetro más.", 0.5,
      None, "CONTENCIÓN", "NO ATACAR.|NO DEJAR CRECER."),
    S("El que la inventó fue un diplomático llamado Yorch Quénan, en un telegrama desde Moscú de ocho mil palabras.", 0.5,
      None, "GEORGE KENNAN", "UN TELEGRAMA DE|8.000 PALABRAS"),
    S("Ocho mil palabras. Un telegrama. En esa época eso costaba una fortuna. Pero cambió la historia del siglo.", 0.55,
      None, "OCHO MIL PALABRAS", "COSTÓ UNA FORTUNA.|CAMBIÓ EL SIGLO."),
    S("Junio de 1947. El general Márshal anuncia el otro brazo del plan, y este es de plata pura.", 0.45,
      None, "JUNIO DE 1947", "AHORA VIENE|LA PLATA"),
    S("Trece mil millones de dólares para reconstruir Europa. Hoy serían más de ciento cincuenta mil millones.", 0.5,
      None, "13.000 MILLONES|DE DÓLARES", "HOY: MÁS DE|150.000 MILLONES"),
    S("Pero ojo, que no era caridad. Era la mejor inversión de la historia americana, y ellos lo sabían perfectamente.", 0.5,
      None, "NO ERA CARIDAD", "ERA LA MEJOR|INVERSIÓN DEL SIGLO"),
    S("Un europeo con trabajo, con pan y con heladera nueva no se hace comunista. Es así de simple, y funcionó.", 0.55,
      None, "LA IDEA ERA|SIMPLE", "CON PAN Y TRABAJO|NADIE SE VUELVE ROJO"),
    S("Stálin prohibió a todos sus países aceptar un solo dólar. Checoslovaquia había dicho que sí; la llamaron a Moscú y dijo que no.", 0.55,
      None, "STALIN LO PROHÍBE", "CHECOSLOVAQUIA DIJO SÍ|Y TUVO QUE DECIR NO"),
    S("Ese día, el mundo quedó oficialmente dividido en dos economías, dos monedas y dos futuros distintos.", 0.6,
      None, "DOS ECONOMÍAS", "DOS MONEDAS|DOS FUTUROS"),
]

GUION += [
    # ------------------------------------------------ 7. EL BLOQUEO DE BERLÍN
    S("Y ahora hablemos de Berlín, porque Berlín es el gran problema de toda esta historia.", 0.45,
      None, "AHORA, BERLÍN", "EL GRAN PROBLEMA|DE TODA LA HISTORIA"),
    S("Alemania quedó partida en cuatro zonas. Pero Berlín, la capital, quedó adentro de la zona soviética. Y también partida en cuatro.", 0.5,
      None, "ALEMANIA:|CUATRO ZONAS", "Y BERLÍN, ADENTRO|DE LA ZONA SOVIÉTICA"),
    S("O sea: media ciudad occidental, flotando como una isla, a ciento sesenta kilómetros adentro del territorio comunista.", 0.55,
      None, "UNA ISLA", "A 160 KM ADENTRO|DEL LADO ROJO"),
    S("Es como tener un pedazo del living del vecino adentro de tu casa. Tarde o temprano eso trae problemas.", 0.5,
      None, "UN PEDAZO DEL|LIVING DEL VECINO", "ADENTRO DE TU CASA"),
    S("Junio de 1948. Los occidentales lanzan una moneda nueva, el marco alemán, para reactivar su parte.", 0.45,
      None, "JUNIO DE 1948", "NACE EL MARCO|ALEMÁN"),
    S("Stálin lo lee como una declaración de guerra económica. Y responde cerrando todo: rutas, trenes y canales.", 0.55,
      None, "STALIN RESPONDE", "CIERRA RUTAS,|TRENES Y CANALES"),
    S("Dos millones y medio de personas quedan encerradas, con comida para treinta y seis días y carbón para cuarenta y cinco.", 0.55,
      None, "2,5 MILLONES|ENCERRADOS", "COMIDA PARA|36 DÍAS"),
    S("El cálculo de Stálin era perfecto: o se van de Berlín, o mando yo los camiones con comida y quedan como unos payasos.", 0.55,
      None, "EL CÁLCULO|DE STALIN", "«O SE VAN,|O QUEDAN COMO PAYASOS»"),
    S("Y ahí a alguien se le ocurre la idea más loca y más hermosa de toda la Guerra Fría.", 0.5,
      None, "Y AHÍ APARECE|UNA IDEA", "LA MÁS LOCA|DE TODA LA GUERRA"),
    S("Si cerraron las rutas... vamos por arriba. Alimentamos una ciudad entera desde el aire. Todos los días.", 0.6,
      None, "«VAMOS POR ARRIBA»", "ALIMENTAR UNA CIUDAD|DESDE EL AIRE"),
    S("Los militares hicieron los números y dijeron que era imposible. Hacían falta cinco mil toneladas por día.", 0.5,
      None, "«ES IMPOSIBLE»", "5.000 TONELADAS|POR DÍA"),
    S("Empezaron trayendo ochenta toneladas. Al final del bloqueo estaban trayendo ocho mil en un solo día.", 0.55,
      None, "EMPEZARON CON 80", "TERMINARON|CON 8.000"),
    S("Un avión aterrizaba en Berlín cada cuarenta y cinco segundos. De día, de noche, con niebla, con nieve, sin parar.", 0.55,
      None, "UN AVIÓN CADA|45 SEGUNDOS", "DE DÍA Y DE NOCHE"),
    S("Trescientos veintisiete días seguidos. Doscientos setenta y siete mil vuelos. Dos millones de toneladas de carga.", 0.55,
      None, "327 DÍAS", "277.000 VUELOS|2 MILLONES DE TONELADAS"),
    S("Llevaron harina, carbón, medicamentos y hasta las piezas de una central eléctrica entera, desarmada en pedacitos.", 0.5,
      None, "HASTA UNA CENTRAL|ELÉCTRICA", "DESARMADA|EN PEDACITOS"),
    S("Y pasó algo que ningún estratega había previsto: un piloto llamado Guéil Jalvórsen empezó a tirar caramelos.", 0.5,
      None, "GAIL HALVORSEN", "EL PILOTO QUE|TIRABA CARAMELOS"),
    S("Les hacía paracaídas con pañuelos y los soltaba antes de aterrizar. Los chicos lo esperaban en las ruinas.", 0.5,
      None, "PARACAÍDAS|CON PAÑUELOS", "LOS CHICOS LO|ESPERABAN ABAJO"),
    S("Le decían el Tío Alas de Caramelo. Y en tres años esos mismos chicos habían dejado de ver a los americanos como enemigos.", 0.6,
      None, "«EL TÍO ALAS|DE CARAMELO»", "GANÓ MÁS QUE|CUALQUIER BOMBA"),
    S("Setenta y ocho personas murieron en accidentes durante el puente aéreo. Nadie disparó un solo tiro.", 0.55,
      None, "78 MUERTOS", "Y NI UN SOLO|DISPARO"),
    S("Mayo de 1949. Stálin abre las rutas y hace de cuenta que no pasó nada. Perdió, y perdió delante de todo el mundo.", 0.6,
      None, "MAYO DE 1949", "STALIN ABRE|LAS RUTAS"),
    S("De ese fracaso nacen dos países: la República Federal Alemana, al oeste, y la República Democrática Alemana, al este.", 0.5,
      None, "NACEN DOS|ALEMANIAS", "UNA AL OESTE|Y OTRA AL ESTE"),
    S("Un mismo pueblo, un mismo idioma, y de golpe dos países que van a odiarse durante cuarenta años.", 0.6,
      None, "UN MISMO PUEBLO", "DOS PAÍSES|CUARENTA AÑOS"),

    # ------------------------------------------------- 8. 1949: EL AÑO NEGRO
    S("Y llegamos a 1949, que para los americanos fue el peor año de toda la Guerra Fría.", 0.45,
      None, "1949", "EL PEOR AÑO|PARA WASHINGTON"),
    S("En abril nace la OTAN: doce países que firman una sola frase clave. Atacar a uno es atacar a todos.", 0.5,
      None, "NACE LA OTAN", "«ATACAR A UNO|ES ATACAR A TODOS»"),
    S("Es la primera vez en su historia que Estados Unidos firma una alianza militar en tiempos de paz. Se acabó el aislamiento.", 0.5,
      None, "PRIMERA ALIANZA|EN PAZ", "SE ACABÓ|EL AISLAMIENTO"),
    S("Pero el 29 de agosto pasa algo que nadie esperaba tan pronto. En el desierto de Kazajistán se levanta un hongo.", 0.55,
      None, "29 DE AGOSTO", "UN HONGO EN|KAZAJISTÁN"),
    S("La Unión Soviética hizo estallar su primera bomba atómica. Los expertos americanos habían calculado que tardarían diez años más.", 0.55,
      None, "LA URSS TIENE|LA BOMBA", "CALCULABAN QUE|TARDABA 10 AÑOS"),
    S("Tardaron cuatro. Y no fue solo talento: fue un físico llamado Klaus Fuchs, que trabajó en la bomba americana y pasó los planos.", 0.55,
      None, "KLAUS FUCHS", "TRABAJÓ EN LA BOMBA|Y PASÓ LOS PLANOS"),
    S("La primera bomba soviética era casi una fotocopia de la americana. Copiaron hasta detalles que ni siquiera hacían falta.", 0.55,
      None, "CASI UNA|FOTOCOPIA", "COPIARON HASTA|LO QUE SOBRABA"),
    S("Y en octubre, la frutilla del postre: Mao gana la guerra civil y China entera se vuelve comunista.", 0.5,
      None, "OCTUBRE DE 1949", "MAO GANA:|CHINA ES COMUNISTA"),
    S("Quinientos millones de personas más del otro lado del tablero. En Washington la pregunta fue: ¿quién perdió China?", 0.55,
      None, "500 MILLONES MÁS", "«¿QUIÉN PERDIÓ|CHINA?»"),
    S("Esa pregunta, hecha con mala leche, va a arruinarle la vida a mucha gente inocente en los años siguientes.", 0.6,
      None, "UNA PREGUNTA|CON MALA LECHE", "LE ARRUINÓ LA VIDA|A MUCHA GENTE"),

    # --------------------------------------------------- 9. LA CAZA DE BRUJAS
    S("Porque cuando un país se asusta, empieza a buscar traidores adentro. Y siempre encuentra, aunque no haya.", 0.5,
      None, "CUANDO UN PAÍS|SE ASUSTA", "BUSCA TRAIDORES|ADENTRO"),
    S("Febrero de 1950. Un senador poco conocido, Yósef Mac Cárthy, levanta un papel en un discurso y dice una barbaridad.", 0.5,
      None, "JOSEPH|McCARTHY", "LEVANTA UN PAPEL|Y DICE UNA BARBARIDAD"),
    S("Tengo acá la lista de doscientos cinco comunistas que trabajan adentro del Departamento de Estado.", 0.55,
      None, "«TENGO ACÁ|LA LISTA»", "«205 COMUNISTAS»"),
    S("Nunca mostró la lista. Nunca existió. El número cambiaba según el día: doscientos cinco, cincuenta y siete, ochenta y uno.", 0.55,
      None, "NUNCA LA MOSTRÓ", "EL NÚMERO CAMBIABA|SEGÚN EL DÍA"),
    S("No importó. Durante cuatro años ese hombre tuvo al país entero temblando frente a un micrófono.", 0.5,
      None, "NO IMPORTÓ", "TUVO AL PAÍS|TEMBLANDO"),
    S("Escritores, actores, profesores y guionistas quedaron en listas negras. Sin juicio, sin pruebas, sin trabajo nunca más.", 0.55,
      None, "LISTAS NEGRAS", "SIN JUICIO|Y SIN TRABAJO"),
    S("A Cháplin, el de las películas mudas, lo echaron del país. Al director Elia Kazán lo perdonaron... por delatar amigos.", 0.55,
      None, "A CHAPLIN|LO ECHARON", "A OTROS LOS SALVÓ|DELATAR AMIGOS"),
    S("Y en 1953 ejecutaron en la silla eléctrica a Yulius y Ézel Rosenberg, acusados de pasar secretos atómicos.", 0.55,
      None, "LOS ROSENBERG", "SILLA ELÉCTRICA|EN 1953"),
    S("Él, probablemente culpable. Ella, casi seguro que no. Dejaron dos hijos de seis y diez años.", 0.6,
      None, "ÉL, CULPABLE.|ELLA, CASI SEGURO NO.", "DEJARON DOS HIJOS"),
    S("Mac Cárthy cayó cuando se metió con el Ejército y la televisión transmitió las audiencias en vivo.", 0.5,
      None, "MCCARTHY CAE", "CUANDO LA TELE|LO MUESTRA EN VIVO"),
    S("Un abogado le preguntó en cámara: ¿no le queda a usted ningún sentido de la decencia, señor?", 0.55,
      None, "«¿NO LE QUEDA|DECENCIA, SEÑOR?»", "LA PREGUNTA|QUE LO HUNDIÓ"),
    S("El país lo vio transpirar. Y en tres años murió olvidado, tomando. Pero el miedo ya estaba instalado para siempre.", 0.6,
      None, "EL PAÍS LO VIO|TRANSPIRAR", "PERO EL MIEDO|YA QUEDÓ"),

    # ------------------------------------------------------- 10. COREA, 1950
    S("Junio de 1950. La Guerra Fría deja de ser fría por primera vez, y pasa en un lugar que casi nadie sabía ubicar.", 0.5,
      None, "JUNIO DE 1950", "LA GUERRA FRÍA|SE PONE CALIENTE"),
    S("Corea había quedado partida al medio por una línea recta trazada en media hora por dos oficiales con un mapa escolar.", 0.55,
      None, "COREA, PARTIDA|AL MEDIO", "UNA LÍNEA TRAZADA|EN MEDIA HORA"),
    S("El paralelo treinta y ocho. Arriba, comunistas. Abajo, americanos. Nadie le preguntó nada a los coreanos.", 0.5,
      None, "EL PARALELO 38", "NADIE LE PREGUNTÓ|A LOS COREANOS"),
    S("El 25 de junio, el norte cruza la línea con tanques soviéticos. En tres días toman la capital del sur.", 0.5,
      None, "25 DE JUNIO", "EL NORTE CRUZA|CON TANQUES"),
    S("Estados Unidos entra con bandera de las Naciones Unidas, porque los soviéticos estaban de berrinche y faltaron a la votación.", 0.55,
      None, "ENTRAN LAS|NACIONES UNIDAS", "LA URSS FALTÓ|A LA VOTACIÓN"),
    S("El general Mac Ártur hace un desembarco brillante en Inchón y da vuelta la guerra en dos semanas.", 0.5,
      None, "MACARTHUR", "DESEMBARCO EN|INCHÓN"),
    S("Pero se entusiasma, avanza hasta la frontera con China, y ahí Mao manda trescientos mil soldados de golpe.", 0.55,
      None, "SE ENTUSIASMA", "MAO MANDA|300.000 SOLDADOS"),
    S("Mac Ártur pide usar bombas atómicas contra China. Trúman lo escucha, se agarra la cabeza y lo echa.", 0.55,
      None, "PIDE USAR|LA BOMBA", "TRUMAN LO ECHA"),
    S("Fue la primera vez que un presidente le paró la mano a un general con la bomba en la mesa. No fue la última.", 0.55,
      None, "LE PARÓ LA MANO|A UN GENERAL", "NO FUE LA ÚLTIMA VEZ"),
    S("La guerra terminó en 1953 exactamente donde había empezado: en el paralelo treinta y ocho.", 0.5,
      None, "TERMINA EN 1953", "EXACTAMENTE DONDE|EMPEZÓ"),
    S("Tres millones de muertos para volver al mismo lugar. Y técnicamente esa guerra nunca terminó: solo hay un armisticio.", 0.6,
      None, "3 MILLONES|DE MUERTOS", "PARA VOLVER AL|MISMO LUGAR"),
]

GUION += [
    # ------------------------------------------- 11. LA BOMBA H Y EL EQUILIBRIO
    S("Mientras se peleaba en Corea, en los laboratorios pasaba algo mucho más grave, y casi nadie lo vio venir.", 0.45,
      None, "MIENTRAS TANTO", "EN LOS LABORATORIOS|PASA ALGO PEOR"),
    S("Noviembre de 1952. Estados Unidos prueba la bomba de hidrógeno en una islita del Pacífico llamada Elugelab.", 0.5,
      None, "NOVIEMBRE|DE 1952", "LA BOMBA|DE HIDRÓGENO"),
    S("Cuando se disipó el humo, la isla ya no estaba. No quedó nada. Un cráter de dos kilómetros bajo el mar.", 0.55,
      None, "LA ISLA|DESAPARECIÓ", "UN CRÁTER DE|2 KILÓMETROS"),
    S("Era mil veces más potente que Jiroshima. Mil veces. Con una sola de esas se borra una ciudad entera y sus alrededores.", 0.55,
      None, "MIL VECES|HIROSHIMA", "UNA SOLA BORRA|UNA CIUDAD ENTERA"),
    S("Nueve meses después, los soviéticos probaron la suya. La carrera ya no era por ganar: era por no quedarse atrás.", 0.55,
      None, "9 MESES DESPUÉS", "LA URSS TAMBIÉN|LA TIENE"),
    S("Y ahí nace el concepto más loco de la historia militar, y sus siglas en inglés significan, justamente, loco.", 0.5,
      None, "NACE UN CONCEPTO|LOCO", "Y SUS SIGLAS|SIGNIFICAN LOCO"),
    S("Destrucción Mutua Asegurada. La idea es simple: si vos me matás, yo te mato. Aunque ya esté muerto.", 0.55,
      None, "DESTRUCCIÓN MUTUA|ASEGURADA", "«SI ME MATÁS,|TE MATO»"),
    S("La paz del mundo pasó a depender de que los dos supieran que atacar era suicidarse. Nada más que de eso.", 0.6,
      None, "LA PAZ DEPENDE|DE UNA COSA", "ATACAR ES|SUICIDARSE"),
    S("En las escuelas americanas los chicos hacían simulacros: agacharse debajo del pupitre y taparse la nuca.", 0.5,
      None, "SIMULACROS|EN LA ESCUELA", "AGACHARSE BAJO|EL PUPITRE"),
    S("Un pupitre de madera contra una bomba de hidrógeno. Todos sabían que no servía para nada. Pero calmaba.", 0.6,
      None, "UN PUPITRE CONTRA|UNA BOMBA H", "NO SERVÍA.|PERO CALMABA."),

    # ------------------------------------------- 12. STALIN MUERE, LLEGA NIKITA
    S("Marzo de 1953. Stálin aparece tirado en el piso de su casa de campo. Y pasa algo increíble: nadie se anima a entrar.", 0.55,
      None, "MARZO DE 1953", "STALIN, TIRADO|EN EL PISO"),
    S("Los guardias tenían tanto miedo de molestarlo que lo dejaron doce horas ahí, sin llamar a un médico.", 0.55,
      None, "12 HORAS|EN EL PISO", "NADIE SE ANIMABA|A MOLESTARLO"),
    S("Ese detalle explica mejor el régimen que cualquier libro. Murió de un derrame, rodeado de gente que le tenía terror.", 0.6,
      None, "ESE DETALLE|LO EXPLICA TODO", "MURIÓ RODEADO|DE TERROR"),
    S("Después de una pelea interna feroz, queda arriba un tipo distinto: Nikita Jrushóv, hijo de mineros, campechano, impredecible.", 0.5,
      None, "NIKITA|KRUSCHEV", "HIJO DE MINEROS.|IMPREDECIBLE."),
    S("En 1956 hace algo que nadie esperaba: en un congreso cerrado, denuncia los crímenes de Stálin durante cuatro horas.", 0.55,
      None, "1956:|EL DISCURSO SECRETO", "DENUNCIA A STALIN|DURANTE 4 HORAS"),
    S("Cuentan que alguien gritó desde el fondo: ¿y usted dónde estaba? Y Jrushóv contestó: ¿quién dijo eso? Silencio total.", 0.55,
      None, "«¿Y USTED|DÓNDE ESTABA?»", "«¿QUIÉN DIJO ESO?»"),
    S("Ahí está, dijo. Yo estaba exactamente donde está usted ahora: callado y muerto de miedo.", 0.6,
      None, "«YO ESTABA|DONDE USTED»", "«CALLADO Y MUERTO|DE MIEDO»"),

    # ----------------------------------------------------- 13. HUNGRÍA Y SUEZ
    S("Pero cuidado, que aflojar la mano tiene consecuencias. En octubre de 1956, Hungría se lo toma en serio.", 0.5,
      None, "OCTUBRE DE 1956", "HUNGRÍA SE LO|TOMA EN SERIO"),
    S("Los estudiantes salen a la calle en Budapest y voltean una estatua gigante de Stálin. Queda solo las botas de bronce.", 0.55,
      None, "VOLTEAN LA|ESTATUA", "QUEDAN SOLO|LAS BOTAS"),
    S("Durante doce días, Hungría fue libre. Sacaron a la policía secreta, formaron gobierno nuevo y pidieron salir del bloque.", 0.5,
      None, "DOCE DÍAS|LIBRE", "GOBIERNO NUEVO|Y SALIR DEL BLOQUE"),
    S("Y por la radio, la Voz de América los alentaba: resistan, la ayuda está en camino, no aflojen.", 0.55,
      None, "LA RADIO|LOS ALIENTA", "«RESISTAN, LA AYUDA|ESTÁ EN CAMINO»"),
    S("El 4 de noviembre entraron dos mil tanques soviéticos. La ayuda nunca llegó. Nunca iba a llegar.", 0.6,
      None, "2.000 TANQUES", "LA AYUDA|NUNCA LLEGÓ"),
    S("Veinte mil muertos. Doscientos mil huyeron. El último mensaje de la radio húngara fue: ayúdennos, ayúdennos, ayúdennos.", 0.6,
      None, "20.000 MUERTOS", "«AYÚDENNOS,|AYÚDENNOS»"),
    S("Y ahí quedó clara la regla no escrita de esta guerra: cada uno hace lo que quiere adentro de su patio. El otro mira.", 0.6,
      None, "LA REGLA|NO ESCRITA", "CADA UNO MANDA|EN SU PATIO"),
    S("Al mismo tiempo, del otro lado del mapa, Inglaterra y Francia se mandan una macana histórica en el Canal de Suez.", 0.5,
      None, "AL MISMO TIEMPO", "LA MACANA|DE SUEZ"),
    S("Invaden Egipto para recuperar el canal, y esta vez el que los frena en seco no es Moscú: es Washington.", 0.55,
      None, "INVADEN EGIPTO", "Y LOS FRENA|WASHINGTON"),
    S("Ahí terminó de morir el viejo mundo. Londres y París entendieron que ya no decidían nada solos. Nunca más.", 0.6,
      None, "MUERE EL|VIEJO MUNDO", "LONDRES Y PARÍS|YA NO DECIDEN SOLOS"),

    # --------------------------------------------- 14. EL SPUTNIK Y EL ESPACIO
    S("4 de octubre de 1957. Una bolita de metal de ochenta y tres kilos empieza a dar vueltas arriba de nuestras cabezas.", 0.5,
      None, "4 DE OCTUBRE|DE 1957", "UNA BOLITA|DE 83 KILOS"),
    S("El Sputnik. Hacía un solo ruido, bip, bip, bip, y ese ruido cualquiera lo podía escuchar con una radio casera.", 0.55,
      None, "EL SPUTNIK", "BIP. BIP. BIP."),
    S("En Estados Unidos ese bip sonaba distinto. Sonaba a: si pueden poner eso ahí arriba, pueden poner una bomba encima de tu casa.", 0.6,
      None, "ESE BIP SONABA|DISTINTO", "«PUEDEN PONER UNA BOMBA|SOBRE TU CASA»"),
    S("Fue un cachetazo al orgullo. Se creían los mejores en todo, y los superó un país que quince años antes araba con caballos.", 0.55,
      None, "UN CACHETAZO|AL ORGULLO", "LOS SUPERÓ EL QUE|ARABA CON CABALLOS"),
    S("Reformaron toda la educación del país, fundaron la NASA y empezaron a tirar plata a la ciencia como nunca antes.", 0.5,
      None, "NACE LA NASA", "Y SE REFORMA|TODA LA EDUCACIÓN"),
    S("En 1961, Yuri Gagarin da la vuelta al planeta y se convierte en el primer hombre en el espacio. Otro cachetazo.", 0.55,
      None, "1961: GAGARIN", "EL PRIMER HOMBRE|EN EL ESPACIO"),
    S("Y por eso, un mes después, Quénedi promete llegar a la Luna antes de que termine la década. Pero esa historia ya te la conté.", 0.6,
      None, "KENNEDY PROMETE|LA LUNA", "PERO ESA HISTORIA|YA TE LA CONTÉ"),

    # -------------------------------------------------- 15. EL MURO DE BERLÍN
    S("Volvamos a Berlín, porque Berlín seguía siendo la herida abierta. Y ahora se estaba desangrando de verdad.", 0.5,
      None, "VOLVAMOS|A BERLÍN", "LA HERIDA|SIGUE ABIERTA"),
    S("El problema para el este era humillante: la gente se iba. Cruzaba a la parte occidental caminando y no volvía.", 0.5,
      None, "LA GENTE|SE IBA", "CRUZABA CAMINANDO|Y NO VOLVÍA"),
    S("En diez años se fueron tres millones de personas. Y no se iban los vagos: se iban los médicos, los ingenieros, los jóvenes.", 0.55,
      None, "3 MILLONES|EN 10 AÑOS", "MÉDICOS, INGENIEROS,|JÓVENES"),
    S("Un país se puede bancar perder plata. Lo que no se puede bancar es perder a su gente formada, todos los meses.", 0.6,
      None, "PERDER PLATA|SE BANCA", "PERDER GENTE|FORMADA, NO"),
    S("La noche del 12 al 13 de agosto de 1961, mientras Berlín dormía, empezaron a desenrollar alambre de púa.", 0.55,
      None, "NOCHE DEL 13|DE AGOSTO DE 1961", "EMPIEZAN A DESENROLLAR|ALAMBRE DE PÚA"),
    S("Cuarenta y tres kilómetros cruzando la ciudad. La gente se despertó y su barrio estaba partido al medio.", 0.55,
      None, "43 KILÓMETROS", "LA CIUDAD PARTIDA|MIENTRAS DORMÍA"),
    S("Familias enteras quedaron de un lado y del otro. Gente que había ido a visitar a la madre no pudo volver a su casa.", 0.55,
      None, "FAMILIAS|PARTIDAS", "FUERON A VISITAR|Y NO VOLVIERON"),
    S("Al alambre lo reemplazaron por bloques, y a los bloques por un muro de hormigón de casi cuatro metros.", 0.5,
      None, "DEL ALAMBRE|AL HORMIGÓN", "CASI CUATRO METROS|DE ALTO"),
    S("Y atrás pusieron lo peor: la franja de la muerte. Arena rastrillada, perros, reflectores y orden de disparar.", 0.55,
      None, "LA FRANJA|DE LA MUERTE", "ARENA, PERROS|Y ORDEN DE DISPARAR"),
    S("El régimen le puso un nombre insólito: muralla de protección antifascista. Como si el muro cuidara a los de adentro.", 0.55,
      None, "LO LLAMARON|«MURALLA DE PROTECCIÓN»", "COMO SI CUIDARA|A LOS DE ADENTRO"),
    S("Pero las torres apuntaban para adentro. Y eso, en un muro, dice absolutamente todo.", 0.6,
      None, "LAS TORRES|APUNTABAN ADENTRO", "Y ESO LO|DICE TODO"),
    S("La gente igual intentó. Saltaron de las ventanas de los edificios de la frontera antes de que las taparan con ladrillos.", 0.5,
      None, "IGUAL INTENTARON", "SALTABAN DE|LAS VENTANAS"),
    S("Cavaron más de setenta túneles. Cruzaron en globo aerostático casero, en tirolesa, escondidos abajo del asiento de un auto.", 0.55,
      None, "70 TÚNELES", "GLOBOS, TIROLESAS|Y AUTOS TRUCADOS"),
    S("En 1962, un chico de dieciocho años, Péter Fechter, quedó baleado al pie del muro y nadie lo levantó.", 0.55,
      None, "PETER FECHTER", "18 AÑOS,|BALEADO AL PIE DEL MURO"),
    S("Estuvo una hora desangrándose, pidiendo ayuda, entre los dos bandos. Los dos lo miraron morir sin cruzar la línea.", 0.6,
      None, "UNA HORA|DESANGRÁNDOSE", "LOS DOS LO|MIRARON MORIR"),
    S("Al menos ciento cuarenta personas murieron en ese muro. El último, nueve meses antes de que lo tiraran abajo.", 0.6,
      None, "AL MENOS 140|MUERTOS", "EL ÚLTIMO, 9 MESES|ANTES DEL FINAL"),
]

GUION += [
    # ------------------------------------------------------------ 16. CUBA I
    S("Y ahora sí, agarrate, porque llegamos a los trece días más peligrosos de la historia de la humanidad.", 0.55,
      None, "AGARRATE", "LOS 13 DÍAS MÁS|PELIGROSOS DE LA HISTORIA"),
    S("Todo empieza en una isla del Caribe a ciento cincuenta kilómetros de la costa de Estados Unidos.", 0.45,
      None, "UNA ISLA|DEL CARIBE", "A 150 KM DE|ESTADOS UNIDOS"),
    S("En 1959, Fidel Castro voltea a un dictador y toma el poder en Cuba. Al principio, ni siquiera se declaraba comunista.", 0.5,
      None, "1959: FIDEL", "AL PRINCIPIO NI SE|DECÍA COMUNISTA"),
    S("Pero nacionaliza las empresas americanas, Washington le corta el azúcar, y Moscú levanta la mano y dice: yo te lo compro.", 0.55,
      None, "LE CORTAN|EL AZÚCAR", "MOSCÚ DICE:|«YO TE LO COMPRO»"),
    S("Abril de 1961. La CIA arma una invasión con exiliados cubanos y los desembarca en Bahía de Cochinos.", 0.5,
      None, "ABRIL DE 1961", "INVASIÓN EN BAHÍA|DE COCHINOS"),
    S("Fue un desastre completo. Los barcos con la munición se hundieron, el apoyo aéreo nunca llegó y en tres días los agarraron a todos.", 0.55,
      None, "UN DESASTRE|COMPLETO", "EN TRES DÍAS|LOS AGARRARON"),
    S("Quénedi quedó como un improvisado. Y Jrushóv sacó una conclusión que casi nos cuesta el planeta: este pibe es blando.", 0.6,
      None, "«ESTE PIBE|ES BLANDO»", "LA CONCLUSIÓN QUE|CASI NOS MATA"),
    S("Así que en 1962 los soviéticos empiezan a meter misiles nucleares en Cuba, en secreto, disfrazados de maquinaria agrícola.", 0.55,
      None, "MISILES EN CUBA", "DISFRAZADOS DE|MAQUINARIA AGRÍCOLA"),
    S("Mandaron cuarenta mil soldados haciéndolos vestir camisas a cuadros, como si fueran turistas. Con abrigos de invierno, en el Caribe.", 0.55,
      None, "40.000 SOLDADOS", "«TURISTAS» CON|ABRIGO EN EL CARIBE"),
    S("El 14 de octubre, un avión espía americano vuela alto sobre la isla y saca unas fotos que van a cambiar todo.", 0.5,
      None, "14 DE OCTUBRE", "UN AVIÓN ESPÍA|SACA FOTOS"),
    S("En las fotos hay rampas de lanzamiento. Desde ahí, un misil llega a Washington en trece minutos. Trece.", 0.6,
      None, "RAMPAS DE|LANZAMIENTO", "WASHINGTON A|13 MINUTOS"),

    # ----------------------------------------------------------- 17. CUBA II
    S("Quénedi junta a sus asesores en una sala y les prohíbe salir. Ahí empiezan los trece días.", 0.5,
      None, "EMPIEZAN LOS|13 DÍAS", "NADIE SALE|DE LA SALA"),
    S("Los militares tenían una sola idea: bombardear la isla y después invadirla. Rápido, fuerte y sin preguntar.", 0.5,
      None, "LOS MILITARES:|BOMBARDEAR", "RÁPIDO, FUERTE|Y SIN PREGUNTAR"),
    S("El jefe de la fuerza aérea, Curtis Lemey, le dijo en la cara que no bombardear era tan cobarde como negociar con Jítler.", 0.55,
      None, "CURTIS LeMAY", "«NO BOMBARDEAR ES|COBARDÍA»"),
    S("Y acá está el detalle que nadie sabía entonces: en Cuba ya había misiles nucleares tácticos, armados y listos.", 0.6,
      None, "LO QUE NADIE|SABÍA", "YA HABÍA MISILES|ARMADOS EN CUBA"),
    S("Si invadían, el comandante soviético en la isla tenía autorización para usarlos sin consultar a Moscú. Se terminaba el mundo esa tarde.", 0.6,
      None, "SI INVADÍAN...", "SE TERMINABA EL|MUNDO ESA TARDE"),
    S("Quénedi elige la opción intermedia: un bloqueo naval. Pero lo llama cuarentena, porque bloqueo es palabra de guerra.", 0.55,
      None, "BLOQUEO NAVAL", "LO LLAMAN|«CUARENTENA»"),
    S("El 22 de octubre sale por televisión y le cuenta al país lo que está pasando. Cien millones de personas escuchando.", 0.5,
      None, "22 DE OCTUBRE", "100 MILLONES|MIRANDO LA TELE"),
    S("Esa noche, en Estados Unidos, se vaciaron los supermercados y se llenaron las iglesias. La gente pensó que era el final.", 0.6,
      None, "SE VACIARON LOS|SUPERMERCADOS", "SE LLENARON|LAS IGLESIAS"),
    S("Veinte barcos soviéticos cargados navegan hacia la línea del bloqueo. Nadie sabe si van a frenar o a seguir de largo.", 0.55,
      None, "20 BARCOS|SOVIÉTICOS", "¿FRENAN O SIGUEN|DE LARGO?"),
    S("El 24 de octubre, a último momento, los barcos frenan y algunos giran. Un asesor dijo la frase famosa.", 0.5,
      None, "24 DE OCTUBRE", "LOS BARCOS FRENAN"),
    S("Estamos ojo con ojo, y creo que el otro acaba de parpadear.", 0.6,
      None, "«OJO CON OJO»", "«Y EL OTRO|PARPADEÓ»"),
    S("Pero todavía faltaba lo peor. Y lo peor pasó abajo del agua, donde nadie estaba mirando.", 0.55,
      None, "FALTA LO PEOR", "Y PASA ABAJO|DEL AGUA"),

    # ---------------------------------------------------------- 18. CUBA III
    S("27 de octubre. Le dicen el sábado negro. Ese día casi se termina todo tres veces distintas.", 0.55,
      None, "EL SÁBADO NEGRO", "CASI SE TERMINA|TODO TRES VECES"),
    S("Primero: derriban un avión espía sobre Cuba y matan al piloto. Estados Unidos tenía orden de responder, y no respondió.", 0.55,
      None, "DERRIBAN|UN AVIÓN", "TENÍAN ORDEN DE|RESPONDER Y NO LO HICIERON"),
    S("Segundo: otro avión americano se pierde y entra por error al espacio aéreo soviético. Salieron cazas a buscarlo.", 0.55,
      None, "UN AVIÓN SE|PIERDE", "Y ENTRA EN|ESPACIO SOVIÉTICO"),
    S("Y tercero, el que más cerca estuvo: un submarino soviético, el bé cincuenta y nueve, escondido cerca del bloqueo.", 0.55,
      None, "EL SUBMARINO|B-59", "ESCONDIDO CERCA|DEL BLOQUEO"),
    S("Estaba hace días sumergido. Cuarenta y cinco grados de calor adentro, sin aire, sin comunicación con Moscú.", 0.55,
      None, "45 GRADOS|ADENTRO", "SIN AIRE Y SIN|COMUNICACIÓN"),
    S("Los americanos empiezan a tirar cargas de práctica para obligarlo a subir. Adentro suena como si los estuvieran bombardeando.", 0.55,
      None, "TIRAN CARGAS|DE PRÁCTICA", "ADENTRO SUENA|A BOMBARDEO"),
    S("El submarino llevaba un torpedo nuclear. Y para lanzarlo hacían falta tres firmas. El capitán dijo que sí. El político dijo que sí.", 0.6,
      None, "UN TORPEDO|NUCLEAR", "HACEN FALTA|TRES FIRMAS"),
    S("El tercero era el segundo comandante de la flotilla, Vasili Arjípov. Y dijo que no. Solo. Contra los dos.", 0.65,
      None, "VASILI ARKHIPOV", "DIJO QUE NO.|SOLO. CONTRA DOS."),
    S("Discutieron a los gritos. Arjípov aguantó, hicieron subir el submarino, y no pasó nada. Nadie se enteró hasta cuarenta años después.", 0.6,
      None, "AGUANTÓ", "NADIE SE ENTERÓ|HASTA 40 AÑOS DESPUÉS"),
    S("Ese hombre, un desconocido, con calor, sin dormir y sin órdenes, evitó la guerra nuclear. Y volvió a su casa como si nada.", 0.65,
      None, "UN DESCONOCIDO", "EVITÓ LA GUERRA|NUCLEAR"),
    S("Mientras tanto, arriba, se arreglaba por debajo de la mesa. Los soviéticos sacan los misiles de Cuba.", 0.5,
      None, "SE ARREGLA|POR ABAJO", "LA URSS SACA|LOS MISILES"),
    S("A cambio, Estados Unidos promete no invadir la isla. Y en secreto, saca sus propios misiles de Turquía, meses después, sin decir nada.", 0.6,
      None, "A CAMBIO", "Y EN SECRETO:|LOS MISILES DE TURQUÍA"),
    S("Los dos salieron diciendo que habían ganado. Y los dos, en privado, quedaron temblando por lo cerca que estuvieron.", 0.6,
      None, "LOS DOS DICEN|QUE GANARON", "LOS DOS QUEDARON|TEMBLANDO"),
    S("Después de eso instalaron el teléfono rojo: una línea directa entre Washington y Moscú, para no depender del correo en la próxima.", 0.55,
      None, "EL TELÉFONO|ROJO", "LÍNEA DIRECTA|WASHINGTON-MOSCÚ"),
    S("Porque se dieron cuenta de algo tremendo: casi se destruye el mundo, y no por maldad. Por malentendidos.", 0.65,
      None, "CASI SE DESTRUYE|EL MUNDO", "NO POR MALDAD:|POR MALENTENDIDOS"),
]

GUION += [
    # ------------------------------------------------------------ 19. VIETNAM
    S("Pero la Guerra Fría casi nunca se peleó entre los dos grandes. Se peleó en los países chicos, con gente ajena.", 0.5,
      None, "NUNCA PELEABAN|ELLOS", "PELEABAN LOS|PAÍSES CHICOS"),
    S("Le decían guerras por delegación. Yo te armo a estos, vos armás a aquellos, y que se maten allá lejos.", 0.55,
      None, "GUERRAS POR|DELEGACIÓN", "«QUE SE MATEN|ALLÁ LEJOS»"),
    S("Y la más larga, la más cara y la más triste de todas fue Vietnam.", 0.55,
      None, "VIETNAM", "LA MÁS LARGA|Y LA MÁS TRISTE"),
    S("Vietnam venía peleando hacía décadas: primero contra los franceses, que se comieron una paliza histórica en Dien Bien Fu.", 0.5,
      None, "PRIMERO CONTRA|FRANCIA", "LA PALIZA DE|DIEN BIEN PHU"),
    S("El país queda partido, como Corea y como Alemania. Norte comunista, sur apoyado por Occidente. Otra vez la misma película.", 0.5,
      None, "OTRO PAÍS|PARTIDO", "OTRA VEZ LA|MISMA PELÍCULA"),
    S("Estados Unidos entra de a poco, por una teoría que sonaba muy convincente en una reunión: la teoría del dominó.", 0.5,
      None, "LA TEORÍA|DEL DOMINÓ", "SONABA MUY BIEN|EN UNA REUNIÓN"),
    S("Si cae Vietnam, cae Laos, después Camboya, después Tailandia, y así hasta que se te cae medio mundo encima.", 0.55,
      None, "SI CAE UNO,|CAEN TODOS", "HASTA QUE SE TE CAE|MEDIO MUNDO"),
    S("Llegaron a tener quinientos cuarenta mil soldados metidos en la selva, del otro lado del planeta.", 0.5,
      None, "540.000|SOLDADOS", "DEL OTRO LADO|DEL PLANETA"),
    S("Tiraron más bombas que en toda la Segunda Guerra Mundial junta. Y no alcanzó, porque no era una guerra de bombas.", 0.55,
      None, "MÁS BOMBAS QUE|EN TODA LA 2ª GUERRA", "Y NO ALCANZÓ"),
    S("Del otro lado había tipos en sandalias hechas con cubiertas de camión, moviéndose por túneles cavados a mano.", 0.55,
      None, "SANDALIAS DE|CUBIERTA DE CAMIÓN", "Y TÚNELES|CAVADOS A MANO"),
    S("Doscientos cincuenta kilómetros de túneles, con hospitales, cocinas y dormitorios abajo de los pies del enemigo.", 0.55,
      None, "250 KM DE|TÚNELES", "HOSPITALES Y COCINAS|BAJO TIERRA"),
    S("Y fue la primera guerra televisada. La gente cenaba mirando muertos reales, en su living, todas las noches.", 0.6,
      None, "LA PRIMERA GUERRA|TELEVISADA", "MUERTOS REALES|EN EL LIVING"),
    S("Eso cambió todo. Porque una cosa es que te cuenten una guerra, y otra muy distinta es que te la muestren mientras comés.", 0.6,
      None, "ESO LO|CAMBIÓ TODO", "TE LA MUESTRAN|MIENTRAS COMÉS"),
    S("Los jóvenes salieron a la calle, quemaron las cartas de reclutamiento y le pusieron música a la protesta.", 0.5,
      None, "SALIERON A|LA CALLE", "QUEMARON LAS CARTAS|DE RECLUTAMIENTO"),
    S("En 1975, los tanques del norte entran a Saigón y las últimas personas escapan colgadas de un helicóptero en la terraza de la embajada.", 0.6,
      None, "1975: CAE SAIGÓN", "ESCAPAN COLGADOS|DE UN HELICÓPTERO"),
    S("Casi sesenta mil soldados americanos muertos. Y más de dos millones de vietnamitas. Para volver, otra vez, a nada.", 0.65,
      None, "60.000 AMERICANOS", "MÁS DE 2 MILLONES|DE VIETNAMITAS"),

    # --------------------------------------------- 20. PRAGA Y LA DISTENSIÓN
    S("Y no vayas a creer que del otro lado la cosa estaba tranquila. En 1968, Checoslovaquia lo intenta de nuevo.", 0.5,
      None, "1968:|CHECOSLOVAQUIA", "LO INTENTA|DE NUEVO"),
    S("Le llamaron la Primavera de Praga: socialismo con rostro humano. Sacaron la censura y la gente empezó a decir lo que pensaba.", 0.55,
      None, "PRIMAVERA|DE PRAGA", "«SOCIALISMO CON|ROSTRO HUMANO»"),
    S("Duró siete meses. En agosto entraron los tanques del Pacto de Varsovia, y los chicos se les sentaron adelante.", 0.55,
      None, "DURÓ 7 MESES", "LOS CHICOS SE SENTARON|FRENTE A LOS TANQUES"),
    S("Un estudiante, Yan Palach, se prendió fuego en la plaza principal para que su país no se acostumbrara a agachar la cabeza.", 0.6,
      None, "JAN PALACH", "SE PRENDIÓ FUEGO|EN LA PLAZA"),
    S("Y sin embargo, en los años setenta pasa algo raro: los dos bloques se cansan. Se sientan a hablar.", 0.5,
      None, "AÑOS 70", "LOS DOS BLOQUES|SE CANSAN"),
    S("Le dicen la distensión. Firman acuerdos para limitar los misiles, hacen visitas, hasta acoplan una nave americana con una soviética en órbita.", 0.55,
      None, "LA DISTENSIÓN", "HASTA SE ACOPLAN|NAVES EN ÓRBITA"),
    S("En 1972, Nícson, el anticomunista más famoso de América, aterriza en China y le da la mano a Mao.", 0.55,
      None, "1972: NIXON|EN CHINA", "LE DA LA MANO|A MAO"),
    S("Fue una jugada de ajedrez brillante: si China y la Unión Soviética ya se odiaban entre ellas, mejor hacerse amigo de una.", 0.55,
      None, "UNA JUGADA|DE AJEDREZ", "SI SE ODIAN,|HACETE AMIGO DE UNA"),
    S("Y así, el bloque comunista dejó de ser un bloque. Nunca más volvió a ser uno solo.", 0.6,
      None, "EL BLOQUE|SE PARTIÓ", "NUNCA MÁS FUE|UNO SOLO"),

    # ------------------------------------------- 21. AFGANISTÁN Y LOS 80
    S("Pero la calma dura poco. Diciembre de 1979: la Unión Soviética invade Afganistán, pensando que era cosa de meses.", 0.5,
      None, "DICIEMBRE|DE 1979", "LA URSS INVADE|AFGANISTÁN"),
    S("Se quedó nueve años. Le dicen el Vietnam soviético, y el nombre le queda perfecto.", 0.55,
      None, "SE QUEDÓ|9 AÑOS", "«EL VIETNAM|SOVIÉTICO»"),
    S("Estados Unidos armó a la resistencia afgana con misiles portátiles capaces de bajar helicópteros. Y eso dio vuelta la guerra.", 0.55,
      None, "MISILES|PORTÁTILES", "BAJABAN HELICÓPTEROS"),
    S("Décadas después, algunos de esos mismos grupos armados iban a terminar apuntándole a quien los armó. Pero esa es otra historia.", 0.6,
      None, "DÉCADAS DESPUÉS", "LES APUNTARON A|QUIENES LOS ARMARON"),
    S("En 1981 llega Rónald Réigan, un actor de películas de vaqueros convertido en presidente, y sube el tono a lo bestia.", 0.5,
      None, "1981: REAGAN", "UN ACTOR DE VAQUEROS|EN LA CASA BLANCA"),
    S("Le dice a la Unión Soviética el imperio del mal, y anuncia un escudo de misiles en el espacio: la Guerra de las Galaxias.", 0.55,
      None, "«EL IMPERIO|DEL MAL»", "Y UN ESCUDO|EN EL ESPACIO"),
    S("Técnicamente era casi imposible. Pero funcionó igual: obligó a Moscú a gastar plata que ya no tenía.", 0.6,
      None, "CASI IMPOSIBLE", "PERO LOS OBLIGÓ|A GASTAR"),
    S("Y en 1983 estuvimos a un botón de la guerra, otra vez, por culpa de una computadora.", 0.55,
      None, "1983", "A UN BOTÓN|POR UNA COMPUTADORA"),
    S("El sistema soviético avisó que venían cinco misiles americanos. El oficial de guardia era Stanislav Petrov.", 0.55,
      None, "STANISLAV|PETROV", "EL SISTEMA AVISA:|«5 MISILES»"),
    S("Petrov pensó una cosa muy simple: si atacan, no mandan cinco. Mandan mil. Esto tiene que ser un error.", 0.6,
      None, "«SI ATACAN,|MANDAN MIL»", "«ESTO ES|UN ERROR»"),
    S("No avisó. Se la jugó. Era el reflejo del sol en las nubes engañando al satélite. Otro desconocido que nos salvó a todos.", 0.65,
      None, "ERA EL SOL|EN LAS NUBES", "OTRO DESCONOCIDO|QUE NOS SALVÓ"),

    # -------------------------------------- 22. GORBACHOV Y LA CAÍDA
    S("Para 1985 la Unión Soviética estaba fundida. Hacía cohetes perfectos, pero la gente hacía cola cuatro horas por un pan.", 0.55,
      None, "1985: LA URSS|ESTÁ FUNDIDA", "COHETES PERFECTOS,|COLA POR EL PAN"),
    S("Ahí llega Mijaíl Gorbachov, más joven, con dos ideas nuevas y dos palabras que dieron la vuelta al mundo.", 0.5,
      None, "MIJAÍL|GORBACHOV", "DOS IDEAS Y|DOS PALABRAS"),
    S("Glásnost: transparencia, se puede hablar. Y perestroika: reestructurar la economía antes de que se caiga sola.", 0.55,
      None, "GLÁSNOST Y|PERESTROIKA", "HABLAR Y|REESTRUCTURAR"),
    S("En 1986 explota el reactor de Chernóbil. Y el régimen hace lo de siempre: no dice nada durante días.", 0.55,
      None, "1986:|CHERNÓBIL", "EL RÉGIMEN|NO DICE NADA"),
    S("La alarma la dio Suecia, a mil kilómetros, porque un empleado entró a trabajar con los zapatos radiactivos.", 0.55,
      None, "LA ALARMA|LA DIO SUECIA", "UN EMPLEADO ENTRÓ|CON LOS ZAPATOS SUCIOS"),
    S("Chernóbil demostró que el secretismo mataba de verdad. Y Gorbachov después dijo que ese fue el principio del final.", 0.6,
      None, "EL SECRETISMO|MATABA", "«FUE EL PRINCIPIO|DEL FINAL»"),
    S("Y cuando aflojó la mano, todo empezó a moverse solo. Polonia, con el sindicato Solidaridad, gana elecciones libres en 1989.", 0.55,
      None, "1989: POLONIA", "SOLIDARIDAD GANA|ELECCIONES LIBRES"),
    S("Hungría abre su frontera con Austria, y miles de alemanes del este se van de vacaciones... y no vuelven nunca.", 0.55,
      None, "HUNGRÍA ABRE|LA FRONTERA", "SE VAN «DE VACACIONES»|Y NO VUELVEN"),

    # ------------------------------------------------- 23. LA NOCHE DEL MURO
    S("Y llegamos al 9 de noviembre de 1989, uno de los días más increíbles del siglo. Porque el muro se cayó por un malentendido.", 0.6,
      None, "9 DE NOVIEMBRE|DE 1989", "EL MURO CAE POR|UN MALENTENDIDO"),
    S("El gobierno del este iba a aflojar un poco las reglas de viaje. Un trámite, con turnos, controlado. Nada más que eso.", 0.5,
      None, "IBAN A AFLOJAR|UN POCO", "UN TRÁMITE|CONTROLADO"),
    S("Le dan el papel a un funcionario, Gúnter Shabovski, que no había ido a la reunión y no entendía bien qué estaba leyendo.", 0.55,
      None, "GÜNTER|SCHABOWSKI", "NO FUE A LA REUNIÓN|Y LEYÓ IGUAL"),
    S("Lo lee en vivo por televisión. Un periodista le pregunta: ¿y desde cuándo rige esto?", 0.55,
      None, "LO LEE|EN VIVO", "«¿DESDE CUÁNDO|RIGE ESTO?»"),
    S("Shabovski revuelve los papeles, se encoge de hombros y dice: por lo que sé... de inmediato, ya.", 0.6,
      None, "«DE INMEDIATO...|YA»", "SEIS PALABRAS QUE|TIRARON UN MURO"),
    S("Miles de personas salieron a los puestos de control. Los guardias llamaban por teléfono y nadie les daba una orden clara.", 0.55,
      None, "MILES EN LOS|PUESTOS DE CONTROL", "Y NADIE DABA|UNA ORDEN"),
    S("Un oficial, Járald Yeguer, harto y sin instrucciones, tomó la decisión más grande de su vida: abran la barrera.", 0.6,
      None, "«ABRAN LA|BARRERA»", "LA DECISIÓN DE|UN SOLO HOMBRE"),
    S("Y la gente cruzó. Se abrazaron, lloraron, subieron arriba del muro con botellas y empezaron a romperlo con martillos y cucharas.", 0.6,
      None, "LA GENTE CRUZÓ", "LO ROMPIERON CON|MARTILLOS Y CUCHARAS"),
    S("Veintiocho años, dos meses y veintisiete días de muro. Y se cayó en una noche, sin un solo tiro, por una frase mal leída.", 0.65,
      None, "28 AÑOS|DE MURO", "CAYÓ EN UNA NOCHE|SIN UN SOLO TIRO"),

    # ---------------------------------------------------------- 24. EL FINAL
    S("Después fue todo cuesta abajo, y rapidísimo. En dos años se desarmó un imperio de setenta años.", 0.5,
      None, "TODO CUESTA|ABAJO", "70 AÑOS SE DESARMAN|EN DOS"),
    S("En agosto de 1991, la línea dura intenta un golpe contra Gorbachov y lo dejan encerrado en su casa de veraneo.", 0.5,
      None, "AGOSTO DE 1991", "GOLPE CONTRA|GORBACHOV"),
    S("Pero les sale mal: Borís Yeltsin se sube arriba de un tanque en el centro de Moscú y la gente se le pone atrás.", 0.55,
      None, "YELTSIN ARRIBA|DE UN TANQUE", "Y LA GENTE|SE LE PONE ATRÁS"),
    S("El 25 de diciembre de 1991, Gorbachov renuncia por televisión. Esa misma noche bajan la bandera roja del Kremlin.", 0.6,
      None, "25 DE DICIEMBRE|DE 1991", "BAJAN LA BANDERA|DEL KREMLIN"),
    S("La subieron por última vez, la doblaron, y arriba pusieron la bandera de Rusia. Sin himno, sin discurso, sin nadie mirando.", 0.6,
      None, "LA DOBLARON|Y LISTO", "SIN HIMNO Y|SIN DISCURSO"),
    S("Así terminó la Guerra Fría: no con una explosión, sino con un tipo firmando un papel y apagando la luz al salir.", 0.65,
      None, "ASÍ TERMINÓ", "NO CON UNA EXPLOSIÓN:|CON UNA FIRMA"),

    # ------------------------------------------------------------ 25. CIERRE
    S("¿Y qué quedó de todo esto? Quedaron mapas nuevos, quince países donde había uno, y una pila de armas que todavía existen.", 0.5,
      None, "¿QUÉ QUEDÓ?", "15 PAÍSES DONDE|HABÍA UNO"),
    S("Quedó también todo lo bueno que salió del apuro: los satélites, internet, la carrera espacial, la energía nuclear civil.", 0.5,
      None, "TAMBIÉN QUEDÓ|LO BUENO", "SATÉLITES, INTERNET,|LA CARRERA ESPACIAL"),
    S("Pero sobre todo quedó una lección incómoda. En cuarenta y cinco años, los dos gigantes nunca se dispararon.", 0.55,
      None, "UNA LECCIÓN|INCÓMODA", "NUNCA SE|DISPARARON"),
    S("Y aún así murieron millones de personas: en Corea, en Vietnam, en Afganistán, en África y en América Latina.", 0.6,
      None, "Y MURIERON|MILLONES", "COREA, VIETNAM,|AFGANISTÁN..."),
    S("Los que apretaban los botones nunca vivieron cerca de los lugares donde caían las bombas. Eso también es parte de la historia.", 0.6,
      None, "LOS DEL BOTÓN|NUNCA ESTABAN CERCA", "DONDE CAÍAN|LAS BOMBAS"),
    S("Y quedó otra cosa, más rara todavía: el mundo no se salvó por los grandes acuerdos ni por los grandes discursos.", 0.55,
      None, "EL MUNDO NO SE|SALVÓ POR ACUERDOS", "NI POR DISCURSOS"),
    S("Se salvó porque un marinero llamado Arjípov dijo que no. Porque Petrov no levantó el teléfono. Porque un guardia abrió una barrera.", 0.65,
      None, "SE SALVÓ POR|TRES PERSONAS", "ARKHIPOV. PETROV.|UN GUARDIA."),
    S("Gente común, cansada, sin nombre, que en un momento cualquiera decidió no hacer lo que le decían.", 0.6,
      None, "GENTE COMÚN", "QUE DECIDIÓ NO HACER|LO QUE LE DECÍAN"),
    S("Los mapas de la Guerra Fría ya no existen. Pero las decisiones de esa gente todavía nos sostienen.", 0.7,
      None, "LOS MAPAS|YA NO EXISTEN", "SUS DECISIONES|TODAVÍA NOS SOSTIENEN"),
    S("Y la próxima vez que escuches que la historia la hacen los que mandan... acordate del submarino, del calor, y del que dijo que no.", 0.9,
      None, "LA HISTORIA NO LA|HACEN LOS QUE MANDAN", "ACORDATE DEL QUE|DIJO QUE NO"),
]
